mysite/authapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import UserDetailView, UserCreateView, LogoutView, MainMenuView, UserUpdateView, logout_view

app_name = 'authapp'

urlpatterns = [
    path('', MainMenuView.as_view(), name='main_menu'),
    path('login/',
         LoginView.as_view(template_name='authapp/login.html',
                           redirect_authenticated_user=True),
         name='login'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),

    path('info/<int:pk>/', UserDetailView.as_view(), name='user_info'),
    path('info/update/<int:pk>/', UserUpdateView.as_view(), name='user_update')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls')),
    path('shop/', include('shopapp.urls'))
]

mysite/shopapp/urls.py
from django.urls import path
from .views import (ShopIndexView,
                    ProductListView,
                    ProductCreateView,
                    ProductDetailView,
                    ProductUpdateView,
                    OrderCreateView,
                    OrderListView,
                    OrderDetailView,
                    OrderUpdateView)

app_name = 'shopapp'

urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),

    path('products/', ProductListView.as_view(), name='product_list'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),

    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('orders/update/<int:pk>/', OrderUpdateView.as_view(), name='order_update')
]

mysite/authapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    age = models.IntegerField(blank=True, default=0)
    email = models.EmailField(max_length=255, null=True, blank=True)

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Product(models.Model):
    class Meta:
        ordering = ['name', 'price']
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return f'Продукт Название={self.name!r})'


class Order(models.Model):
    verbose_name = _('Order')
    verbose_name_plural = _('Orders')

    delivery_address = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')

mysite/shopapp/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = 'name', 'price', 'description', 'discount'

mysite/authapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView, UpdateView
from .models import Profile


class UserDetailView(DetailView):
    template_name = 'authapp/user_info.html'
    context_object_name = 'user'
    queryset = User.objects.filter(is_active=1)


class UserCreateView(CreateView):
    form_class = UserCreationForm
    template_name = 'authapp/register.html'
    success_url = reverse_lazy('authapp:main_menu')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')

        user = authenticate(
            self.request,
            username=username,
            password=password
        )
        login(request=self.request, user=user)
        return response


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('authapp:login')


def logout_view(request: HttpRequest):
    logout(request)
    return redirect(reverse('authapp:login'))


class MainMenuView(TemplateView):
    template_name = 'authapp/main_menu.html'


class UserUpdateView(UpdateView):
    model = Profile
    fields = 'age', 'bio', 'email'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'authapp:user_info',
            kwargs={'pk': self.object.pk}
        )

mysite/shopapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.http import HttpRequest
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from .models import Product, Order
from .forms import ProductForm


class ShopIndexView(View):
    def get(self, request: HttpRequest):
        return render(request, 'shopapp/index.html')


class ProductListView(ListView):
    template_name = 'shopapp/products_list.html'
    context_object_name = 'products'
    queryset = Product.objects.all()


class ProductCreateView(CreateView):
    model = Product
    fields = 'name', 'price', 'description', 'discount'
    success_url = reverse_lazy('shopapp:product_list')


class ProductDetailView(DetailView):
    template_name = 'shopapp/product_detail.html'
    context_object_name = 'product'
    queryset = Product.objects.all()


class ProductUpdateView(UpdateView):
    model = Product
    template_name_suffix = '_update_form'
    form_class = ProductForm

    def get_success_url(self):
        return reverse(
            'shopapp:product_detail',
            kwargs={'pk': self.object.pk}
        )


class OrderListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects.select_related('user').prefetch_related('products').all()
    )


class OrderCreateView(CreateView):
    model = Order
    fields = 'user', 'delivery_address', 'products'
    success_url = reverse_lazy('shopapp:order_list')


class OrderDetailView(DetailView):
    queryset = (
        Order.objects.select_related('user').prefetch_related('products').all()
    )


class OrderUpdateView(UpdateView):
    model = Order
    fields = 'delivery_address', 'products'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:order_detail',
            kwargs={'pk': self.object.pk}
        )

mysite/authapp/templates/authapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вход</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Вход</button>
    </form>

    <div>
        Нет аккаунта? <a href="{% url 'authapp:register' %}">Регистрация</a>
    </div>


</body>
</html>

mysite/authapp/templates/authapp/main_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добро пожаловать</title>
</head>
<body>
    {% if user.is_authenticated %}
    {% csrf_token %}
        <h1>Здравствуйте, {{user.username}}</h1>

    <h2>Навигация по сайту</h2>
    <div>
        <a href="{% url 'authapp:user_info' pk=user.pk%}">Профиль</a>
    </div>

    <div>
        <a href="{% url 'shopapp:product_list' %}">Перейти к списку товаров</a>
    </div>

    <div>
        <a href="{% url 'shopapp:order_list' %}">Перейти к списку заказов</a>
    </div>
    {% else %}
        <div>
            <h1>Для дальнейшего пользования сайта, вам необходимо войти в аккаунт</h1>
        </div>
        <div>
            <a href="{% url 'authapp:login' %}">Вход</a>
        </div>
    {% endif %}
</body>
</html>

mysite/authapp/templates/authapp/profile_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Обновление профиля</title>
</head>
<body>
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Обновить</button>
        </form>
    </div>

    <div>
        <a href="{% url 'authapp:user_info' pk=object.pk %}">Вернуться</a>
    </div>

</body>
</html>

mysite/authapp/templates/authapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>

    <div>
        Есть аккаунт? <a href="{% url 'authapp:login' %}">Вход</a>
    </div>
</body>
</html>

mysite/authapp/templates/authapp/user_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Профиль</title>
</head>
<body>
    {% if user.is_authenticated %}
        <h2>Информация</h2>
        <p>Имя пользователя: {{user.username}}</p>
        <p>Возраст: {{user.profile.age}}</p>
        <p>Email: {{user.profile.email}}</p>
        <p>Описание: {{user.profile.bio}}</p>
        <a href="{% url 'authapp:logout' %}">Выход из аккаунта</a>
    {% else %}
        <h2>Пользователь не найден</h2>
        <p>
            <a href="{% url 'authapp:user_login' %}">Вход</a>
        </p>
    {% endif %}

    <div>
        <a href="{% url 'authapp:user_update' pk=object.pk %}">Обновить профиль</a>
    </div>

    <div>
        <a href="{% url 'authapp:main_menu' %}">Вернуться в меню</a>
    </div>

</body>
</html>

mysite/shopapp/templates/shopapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Магазин</title>
</head>
<body>
    <h1>Войдите, чтобы начать пользование сайтом</h1>

    <div>
        <a href="{% url 'authapp:login' %}">Вход</a>
    </div>
</body>
</html>

mysite/shopapp/templates/shopapp/order_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Детали заказа</title>
</head>
<body>
    <h1>Заказ №{{object.pk}}</h1>
    <div>
        <p>Заказ сделан пользователем: {{object.user.username}}</p>
        <p>Адрес доставки: {{object.delivery_address}}</p>
        <div>
            Продукты в заказе
        </div>
        <ul>
            {% for product in object.products.all %}
                <li>{{product.name}}: {{product.price}}</li>
            {% endfor %}
        </ul>
    </div>

    <div>
        <a href="{% url 'shopapp:order_list' %}">Вернуться к списку заказов</a>
    </div>

    <div>
        <a href="{% url 'shopapp:order_update' pk=object.pk %}">Обновить заказ</a>
    </div>

</body>
</html>

mysite/shopapp/templates/shopapp/order_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Создание заказа</title>
</head>
<body>
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Создать</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:order_list' %}">Вернуться к списку заказов</a>
    </div>
</body>
</html>

mysite/shopapp/templates/shopapp/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список заказов</title>
</head>
<body>
    <h1>Заказы</h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
                <h2>
                    <a href="{% url 'shopapp:order_detail' pk=order.pk %}">
                        Заказ № {{order.pk}}
                    </a>
                </h2>
            {% endfor %}
        </div>
    {% else %}
        <h3>Список заказов пуст</h3>
    {% endif %}
    <div>
        <a href="{% url 'shopapp:order_create' %}">Создать новый заказ</a>
    </div>

    <div>
        <a href="{% url 'shopapp:product_list' %}">Перейти к списку товаров</a>
    </div>

    <div>
        <a href="{% url 'authapp:main_menu' %}">Вернуться в меню</a>
    </div>

</body>
</html>

mysite/shopapp/templates/shopapp/order_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Обновить заказ</title>
</head>
<body>
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Обновить</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:order_detail' pk=object.pk %}">
            Вернуться к заказу № {{object.pk}}
        </a>
    </div>

</body>
</html>

mysite/shopapp/templates/shopapp/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Детали товара № {{ product.pk }}</title>
</head>
<body>
    <h1>{{ product.name }}</h1>
    <div>
        Описание: {{ product.description }}
    </div>
    <div>
        Цена: {{ product.price }}
    </div>
    <div>
        Скидка: {% firstof product.discount '0' %}
    </div>

    <div>
        <a href="{% url 'shopapp:product_update' pk=product.pk %}">Обновить товар</a>
    </div>

    <div>
        <a href="{% url 'shopapp:product_list' %}">Вернуться к списку продуктов</a>
    </div>

</body>
</html>

mysite/shopapp/templates/shopapp/product_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Создание нового продукта</title>
</head>
<body>

    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Создать</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:product_list' %}">Вернуться к списку продуктов</a>
    </div>
</body>
</html>

mysite/shopapp/templates/shopapp/product_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Обновление товара</title>
</head>
<body>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Обновить</button>
        </form>
    </div>
    <a href="{% url 'shopapp:product_detail' pk=object.pk %}">Вернуться к товару №{{ object.pk }}</a>
</body>
</html>

mysite/shopapp/templates/shopapp/products_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список товаров</title>
</head>
<body>
    <h1>Товары</h1>
    {% if products %}
        <div>
            {% for product in products %}
                <p>
                    Товар: <a href="{% url 'shopapp:product_detail' pk=product.pk %}">{{product.name}}</a>
            {% endfor %}

        </div>
    {% else %}
        <h1>Список продуктов пуст</h1>
    {% endif %}
    <div>
        <a href="{% url 'shopapp:product_create' %}">Создать новый продукт</a>
    </div>

    <div>
        <a href="{% url 'shopapp:order_list' %}">Перейти к списку заказов</a>
    </div>

    <div>
        <a href="{% url 'authapp:main_menu' %}">Вернуться в меню</a>
    </div>

</body>
</html>